### ISSUE TITLE
Redirect problems

### ISSUE THREAD

**Issue by dschraudner** [kianschmalenbach/rdf-browser#10]
It quite often occurred to me that a redirect with  the RDF browser turned on results in an error while it perfectly works with the RDF browser turned off.

Example:

When I go to https://www.google.com/search?q=%40rdfjs%2Fparser-jsonld and click on the first search result, I am not redirected to https://www.npmjs.com/package/@rdfjs/parser-jsonld as I should but instead get an error:

```
File not found

Firefox can’t find the file at moz-extension://afa005ad-99d2-49df-91c6-eb950f3d9a28/package/@rdfjs/parser-jsonld.
```

`moz-extension://afa005ad-99d2-49df-91c6-eb950f3d9a28/package/@rdfjs/parser-jsonld` is also displayed in my address bar.

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for the feedback. I just committed a fix for this issue, it will be included in the upcoming release.
