### ISSUE TITLE
Relative URIs in JSON-LD

### ISSUE THREAD

**Issue by dschraudner** [kianschmalenbach/rdf-browser#11]
When opening a JSON-LD document that contains relative URIs the document location should be used as base URI to create an absolute URI. The JSON-LD parser being used fails at this because no baseIRI is given to the parser and thus the relative URIs are handled incorrectly.

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for the feedback. I just committed a fix for this issue, it will be included in the upcoming release.
