### ISSUE TITLE
Add 'Accept: text/n3' request header

### ISSUE THREAD

**Issue by MattesWhite** [kianschmalenbach/rdf-browser#13]
I have a rather old vocabulary: www.w3.org/2002/12/cal/ical

Sadly, the content negotiation is not properly implemented on this resource. 

Part of the response with `Accept: text/turtle` header:
```
alternates: 
  {"ical.rdf" 1 {type applications/rdf+xml} {charset utf-8} {length 71392}}, 
  {"ical.shex" 1 {type text/shex} {length 21083}}, 
  {"ical.n3" 0.89 {type text/n3} {length 37529}}
``` 
You see the `application`**s**`/rdf+xml` type :upside_down_face: ?

I recognized that a few older resources offer the `text/n3` type. Usually, these are basic Turtle files so parsing such files with the standard Turtle parser should be sufficient in most cases.

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for your feedback. I just added the respective fix to the codebase, it will be included in the next release.
