### ISSUE TITLE
Switch RDF browser on (or off) for one lookup

### ISSUE THREAD

**Issue by aharth** [kianschmalenbach/rdf-browser#14]
Sometimes it would be nice to switch on (or off) the RDF browser for one lookup.

Let's say I am at [1] and would like to see the HTML representation (FWIW, [1] gets redirect to [2]).

I would have to add [1] (and possibly [2]) to the blacklist to see the HTML.

Conversely, if the RDF browser is off and I am at a HTML page (but would like to request the resource in an RDF representation), I need to switch on the RDF browser via about:addons and reload the page.

A simple button quickly accessible to switch between the two variants of the Accept headers (I think that is all that is necessary) would speed up my browsing quite a bit.

[1] https://doi.org/10.1145/3306128
[2] https://data.crossref.org/10.1145%2F3306128

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for your feedback. I just added the respective feature to the codebase, it will be included in the next release.
