### ISSUE TITLE
Relative URIs in Turtle

### ISSUE THREAD

**Issue by aharth** [kianschmalenbach/rdf-browser#18]
The RDF browser (or the upstream Turtle parser) seems to have problems with relative URIs.

E.g., http://paul.ti.rw.fau.de/~ec69etyl/foo/bar/bar.ttl is rendered as:

</foo.ttl#s> </foo.ttl#p> </foo.ttl#o> .

but should be

<../foo.ttl#s> <../foo.ttl#p> <../foo.ttl#o> .

Possibly related to #11?

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for the feedback. I just committed a fix for this issue, it will be included in the upcoming release.
