### ISSUE TITLE
Empty URIs are fine

### ISSUE THREAD

**Issue by kaefer3000** [kianschmalenbach/rdf-browser#2]
Hi,

the following file causes an error (Invalid IRI) to be thrown:
````turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
<> rdfs:seeAlso <semantics> .
````
Cheers!

**Comment by kianschmalenbach** [comment]
Hi,

Thanks for your feedback, the issue is resolved in the current version (1.0.3) of the plugin.

Cheers!
