### ISSUE TITLE
Reloading HTTP links

### ISSUE THREAD

**Issue by kernc** [kianschmalenbach/rdf-browser#21]
Issue: Each time one clicks on a reference to an entity in a current document, the document is _reloaded_. This is a result of the references normally pointing to `http:` protocol whereas the documents are sometimes served over `https:` protocol.

Reproducible example:
1. Go to http://www.w3.org/2000/01/rdf-schema#label (notice being redirected to https).
2. Click on any `rdfs:` link.
3. Notice the page being reloaded.

Instead, one ought to just jump to the appropriate section by a change of hash fragment, without re-retrieving the document.

I recommend to clean the entity's URL here:
https://github.com/kianschmalenbach/rdf-browser/blob/5e3749a5a23dcc7bc739df2817b34d5556360259/src/bdo/resource.js#L78-L79
Something like:
```js
function relativize_url(url) {
    let url = new URL(url);
    if (url.host == window.location.host && 
            url.pathname == window.location.pathname)
        return url.hash;
    return url.href;
}

...

link.setAttribute("href", encodeURI(relativize_url(this.value))); 
```

Excellent addon!
Cheers,

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for your feedback! This issue should be fixed with current version 1.2.0.

Cheers,
Kian
