### ISSUE TITLE
Make blank nodes clickable

### ISSUE THREAD

**Issue by kaefer3000** [kianschmalenbach/rdf-browser#3]
Hi,

in RDF files bigger than my screen, it would be helpful to make blank nodes clickable to ease navigation, similar to fragment identifiers in the same file. For instance, see [the SSN ontology](https://www.w3.org/ns/ssn/).

Cheers!

**Comment by kianschmalenbach** [comment]
Hi,

The current release now includes clickable blank nodes.

Cheers!
