### ISSUE TITLE
Add custom extensions?

### ISSUE THREAD

**Issue by Potherca** [kianschmalenbach/rdf-browser#31]
First of all: great plugin! I love how much easier this has made my life!

Now, my issue... In the settings, I can select "Considered File Extensions"

![image](https://user-images.githubusercontent.com/195757/138453240-6a9c3f85-df12-4f84-90a8-d81fd06cf3ad.png)

One of the projects I am currently working with uses the `.n3` file extension for Turtle/N3.

Is there a way I could add this as an extension to be considered by the plugin?

**Comment by aharth** [comment]
The N3 syntax (and data model) goes beyond Turtle.

If the RDF Browser would claim to support N3 but choke on variables ("?") and quoted graphs ("{ }"), we would have another problem.

**Comment by Potherca** [comment]
I thought that, because the [n3](https://www.npmjs.com/package/n3) package is used, N3 would also be supported :shrug: 

But my original point still stand. I have, once again, run into a project that uses custom extension. Because the MIME type is not set (it just servers everything as plain-text) the file is not enhanced by this plugin. Being able to add a custom file extension would be of much help...
