### ISSUE TITLE
Click to deactivate rdf-browser

### ISSUE THREAD

**Issue by kaefer3000** [kianschmalenbach/rdf-browser#6]
Hi,

if a server incorrectly sends an RDF header, eg. [this random garden planner](https://traumgarten.obi.de/beetplaner/inspirationen/), could there be a button to deactivate rdf-browser for the whole domain/session?

Cheers,

Tobias

**Comment by kianschmalenbach** [comment]
Hi Tobias,

Thank you for your feedback. This feature is included in today's release of the Add-on. You will find the button on the right side of the address bar and you will be able to disable (or forcedly enable) the plugin for each page or directory as well as for the whole domain. Furthermore, you can manually edit the blacklist and whitelist on the Add-on's settings page at _about:addons_.

Cheers,
Kian
