### ISSUE TITLE
Empty relative reference

### ISSUE THREAD

**Issue by aharth** [kianschmalenbach/rdf-browser#7]
The file at 
https://ci.mines-stetienne.fr/kg/index.ttl

contains triples with <> as subject.

However, the plugin changes <> to <#>:

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<#> rdfs:label "RDF file with links to other relevant RDF files for the summer school" ;
    rdfs:seeAlso <itm.ttl> .

**Comment by kianschmalenbach** [comment]
Hi,
Thanks for the feedback. I just committed a fix for this issue, it will be included in the upcoming release.
